### ISSUE TITLE
[Request] Separate stubs into its own package

### ISSUE THREAD

**Issue by nihaals** [python-trio/trio-typing#27]
If you are using another type checker, for example pyright, you can still benefit from having stubs but do not need the mypy plugin (or the mypy dependency) so it would be nice to have 2 separate PyPI packages, one with just the stubs and another with the mypy extension and other addons. Poetry also doesn't seem to support installing specific subpackages (although you would still have the mypy dependency)

**Comment by oremanj** [comment]
We no longer pull in mypy unless you use `pip install trio-typing[mypy]`. I think this obviates the need for separate packages?
