### ISSUE TITLE
trio.open_memory_channel requires explicit type declaration

### ISSUE THREAD

**Issue by math2001** [python-trio/trio-typing#6]
```python
sendch, getch = trio.open_memory_channel(0)
```

mypy wants

```python
sendch, getch = trio.open_memory_channel(0) # type: trio.abc.SendChannel, trio.abc.ReceiveChannel
```

Shouldn't mypy be able to infer the types by itself?

**Comment by math2001** [comment]
I just looked at the source code, and saw [this line](https://github.com/python-trio/trio-typing/blob/0601159facbea506c71a260d0861959bf238f7be/trio-stubs/__init__.pyi#L246). So, I had to do this:

```python
sendch, getch = trio.open_memory_channel[sometype](0)
```

Was this documented somewhere I missed? Maybe it should be added to the README.

**Comment by oremanj** [comment]
The error message that mypy produces is `Need type annotation for '<name of variable>'`, which is the same error you get if you write `some_list = []` in a context where mypy can't infer the type. The solution in both cases is to add the type parameter.

I agree that this error is confusing; filed #9 to track the documentation improvement that's needed here.
