### ISSUE TITLE
Type mismatch between open_signal_receiver and Process.send_signal

### ISSUE THREAD

**Issue by Redoubts** [python-trio/trio-typing#78]
I'm playing with 0.8.0, and I noticed that `trio.open_signal_receiver` gives me an `AsyncIterator[int]`, but `trio.Process.send_signal` takes `Signal`s. Ideally I'd be able to pass one into the other without a cast or type-ignore.

**Comment by A5rocks** [comment]
I believe this is fixed in `trio`'s new inline type hints? `trio.Process.send_signal` takes `int | Signal`s so you should be able to pass in `int`s.
