### ISSUE TITLE
Are tests intended to be distributed?

### ISSUE THREAD

**Issue by dhirschfeld** [python-trio/trio-typing#86]
After installing `trio-typing` using the `pypi` wheel I see the below files being installed:
```
❯ tree -I __pycache__ /opt/mambaforge/envs/test/lib/python3.10/site-packages/trio_typing
/opt/mambaforge/envs/test/lib/python3.10/site-packages/trio_typing
├── __init__.py
├── __init__.pyi
├── _tests
│   ├── __init__.py
│   ├── datadriven.py
│   ├── test-data
│   │   ├── async_generator.test
│   │   ├── open-mode.test
│   │   ├── outcome.test
│   │   ├── taskstatus.test
│   │   └── trio-basic.test
│   ├── test_runtime.py
│   └── test_typecheck.py
├── _version.py
├── plugin.py
└── py.typed

2 directories, 14 files
```

Are the tests intended to be distributed - I think that's not usual?

**Comment by dhirschfeld** [comment]
Not a big issue, just posting for informational purposes.

If this library is merged into `trio` itself (as suggested in https://github.com/python-trio/trio-typing/issues/75) then this is moot, so can probably just wait until that happens.

**Comment by oremanj** [comment]
I did it this way because Trio did. I don't have a strong opinion, but since this is about to be obsoleted by Trio upstream type hints, I'm not going to rock the boat at the moment.
