### ISSUE TITLE
release for mypy 1.4 fix

### ISSUE THREAD

**Issue by belm0** [python-trio/trio-typing#88]
please keep this open until fix for mypy 1.4 (#84) is released, so that there is a visible and trackable issue for people hitting the issue

**Comment by VincentVanlaer** [comment]
@oremanj Since you made the previous releases, would it be possible for you to make a release with these changes? I'm happy to assist if necessary.

**Comment by Redoubts** [comment]
https://github.com/python-trio/trio-typing/releases/tag/v0.9.0

**Comment by VincentVanlaer** [comment]
https://pypi.org/project/trio-typing/0.9.0/
